### PR TITLE
Fixed: node_modules, build folder push on source repo

### PR DESCRIPTION
**Pull request by immayurpanchal**
In React Project, node_modules and build are generated on client side. Pushing those on source repo in not recommended. Please provide your valuable feedback if it was done intentionally. This PR will reduce the size of cloning repo for other devs instead of fetching the entire node_modules, build folder which gets generated every time wherever you deploy your react project. I would love to contribute more to this project. Waiting for this PR to be merged. Thanks :smile:

### CODE REVIEW

**Comment by immayurpanchal** [comment]
@Ishaan28malik , I've also updated Readme.md file to install dependencies and also there is already written info about creating production build. Current repo size is too large. Please check screenshot (32MB)

Screenshot from 2020-10-03 15-22-00

**Review by Ishaan28malik — APPROVED** [review]

**Comment by Ishaan28malik** [comment]
@immayurpanchal good work.

**Comment by immayurpanchal** [comment]
@Ishaan28malik , thanks a lot. Can you please assign labels to this PR.

**Comment by immayurpanchal** [comment]
@Ishaan28malik , Need your help here. PR is merged but labels are missing so it is not counted. 

Screenshot from 2020-10-03 19-03-48
Screenshot from 2020-10-03 19-01-53

**Comment by Ishaan28malik** [comment]
@immayurpanchal thnx for contributing.
Keep contributing and if you like the projects please follow me .

**Pull request merged**
